config/routes.rb
HotTabBook::Application.routes.draw do
  devise_for :users
  scope :module => "admin" do
  resources :homes do
    collection  do
      get :dashboard
      get :invite
      post :send_invite

    end
  end
  end

  resources :home
  resources :hotels do
    resources :bookings
    resources :galleries
    collection  do
      get :dashboard
    end
  end  

  root :to => 'home#index'
  devise_scope :user do
    match'/admin', :to => "devise/sessions#new"
    get "/users/sign_in", :to => "devise/sessions#new"
    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :table

  attr_accessible :email, :phone_number, :time_slot, :user_name, :table_id
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :title,:images_attributes

  belongs_to :hotel
  has_many :images
  accepts_nested_attributes_for :images
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone_number, :website, :city, :main_image
  mount_uploader :main_image, AvatarUploader

  belongs_to :user

  has_many :tables
  has_many :bookings
  has_one :sitemap
  has_one :gallery

  def find_hotel_by_city(city)
  c = city.downcase
  Hotel.select{|hotel| hotel.city==city}
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :data
  mount_uploader :data, AvatarUploader
  belongs_to :gallery
end

app/models/sitemap.rb
class Sitemap < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :hotel
end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :capacity, :description, :table_number

  belongs_to :hotel
  belongs_to :booking
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:admin

  # attr_accessible :title, :body

  has_one :hotel
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def dashboard
    @hotels = Hotel.all
  end

  def invite

  end

  def send_invite
  logger.info"##########{params.inspect}"
  email = params[:email]
  UserMailer.invite_hotel(email).deliver
  flash[:notice] = "Email sent successfully"
  redirect_to dashboard_homes_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    current_user.admin? ?  dashboard_homes_path :  dashboard_hotels_path
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@current_time = Time.now
  	hotel = Hotel.find(params[:hotel_id])
  	@booking = hotel.bookings.new
  	@bookings = hotel.bookings.where('time_slot',@current_time)
  	@booked_tables = @bookings.collect{|p| p.table_id}
  end
  def create
  	hotel = Hotel.find(params[:hotel_id])
  	hotel.bookings.create(params[:booking])
  	redirect_to :action => :new
  end	
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def new
  logger.info"############{params.inspect}"
  @hotel = Hotel.find(params[:hotel_id])
  @gallery = @hotel.build_gallery
    10.times do
      @image = @gallery.images.build
    end
  end

  def create
    logger.info"##########{params.inspect}"
  @hotel = Hotel.find(params[:hotel_id])
  @gallery = @hotel.build_gallery(params[:gallery])
    if @gallery.save
      redirect_to hotels_path
    else
    render 'new'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@hotels = Hotel.all
	end	
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def new
  	@hotel = current_user.build_hotel
  end
  
  def create
    params[:hotel][:city] = params[:hotel][:city].downcase
    @hotel =current_user.build_hotel(params[:hotel])
    @hotel.save
    redirect_to dashboard_hotels_path
  end
  
  def index

  end

  def dashboard
    @hotel = current_user.hotel
    logger.info"#########{@hotel.inspect}"
  end

  def bookings

  end

  def edit
  @hotel = current_user.hotel
  end

  def update
  @hotel = current_user.hotel
    if @hotel.update_attributes(params[:hotel])
      redirect_to dashboard_hotels_path
    else
      render 'edit'
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/gallaries_helper.rb
module GallariesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/homes/dashboard.html.erb
<%= link_to "Invite Hotels", invite_homes_path,:class=>"btn btn-primary btn-large invite_tab"%>

app/views/admin/homes/invite.html.erb
<%= form_tag(send_invite_homes_path,:method => 'post') do %>
<%= text_field_tag "email",nil, :class => 'email',:placeholder => "Enter Hotel's email" %>
<%= submit_tag 'Invites' %>
<% end %>

app/views/bookings/index.html.erb
<% if @bookings.present? %>
    <h1>Booking Details</h1>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th>User Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Time Slot</th>
      </tr>
      </thead>
      <tbody>
      <% @bookings.to_enum.with_index(1) do |booking, index| %>
          <tr>
            <td><%= index %></td>
            <td><%= booking.user_name %></td>
            <td><%= booking.email %></td>
            <td><%= booking.phone_number %></td>
            <td><%= booking.time_slot %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/bookings/new.html.erb
<%= stylesheet_link_tag "jquery-ui" %>
<%= stylesheet_link_tag "booking" %>
<%= stylesheet_link_tag "jquery.fancybox" %>
<%= javascript_include_tag "bookings" %>
<div class="bookedTables" rel='<%= @booked_tables %>'>
<div class="hotelName clearfix">
      <div class="container">
        <div class="clearfix"></div>
        <section class="hotelLayout">
          <div class="topTables">
            <ul class="clearfix">
              <li class="tables">
                <ul class="clearfix">
              <li><a href="#registration_form" id="1" class="topTable">&nbsp;</a>
	              <div class="tableDetails" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
			  </li>
              <li><a href="#registration_form" id="2" class="topTable">&nbsp;</a>
              	<div class="tableDetails" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
            </ul>
            <ul class="clearfix">
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails1" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails1" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails1" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
              <li><a href="#registration_form" class="topTable">&nbsp;</a>
              	<div class="tableDetails1" style="display: none;">
			        <p>Capacity : <%= %></p>
			        <p>Note : <%= %></p>
			      </div>
              </li>
            </ul>
            </li>
            <li>
              <div class="washroomTop">Washroom</div>
            </li>
            <li>
              <div class="specialRooms">
                <div class="table1">
                  <a href="#">&nbsp;</a>
                </div>
                <div class="table2">
                  <a href="#">&nbsp;</a>
                </div>
              </div>
            </li>

            </ul>
          </div>
          <div class="reception">
            <span><img src="/assets/entry.jpg"></span>
            <img src="/assets/waitingRoom.jpg">
            <img src="/assets/kitchen.jpg"/>
          </div>
          <div class="swimingPool"></div>
          <div class="bottomTable">
            <ul class="clearfix">
              <li>
                <ul class="clearfix">
                  <li class="tables">
                    <ul class="clearfix">
                      <li><a href="#registration_form" class="topTable" >&nbsp;</a>
                      	<div class="tableDetails2" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			            </div>
                      </li>
                      <li><a href="#registration_form" class="topTable">&nbsp;</a>
                      	<div class="tableDetails2" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			            </div>
                      </li>
                      <li><a href="#registration_form" class="topTable">&nbsp;</a>
                      	<div class="tableDetails2" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			            </div>
                      </li>
                      <li><a href="#registration_form" class="topTable">&nbsp;</a>
                      	<div class="tableDetails2" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			            </div>
                      </li>
                    </ul>
                  </li>
                </ul>
              <li>
              <li>
                <ul class="clearfix">
                  <li><a href="#registration_form" class="topTable">&nbsp;</a>
                  	<div class="tableDetails3" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			        </div>
                  </li>
                  <li><a href="#registration_form" class="topTable">&nbsp;</a>
                  	<div class="tableDetails3" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			        </div>
                  </li>
                  <li><a href="#registration_form" class="topTable">&nbsp;</a>
                  	<div class="tableDetails3" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			        </div>
                  </li>
                  <li><a href="#registration_form" class="topTable">&nbsp;</a>
                  	<div class="tableDetails3" style="display: none;">
			              <p>Capacity : <%= %></p>
			              <p>Note : <%= %></p>
			        </div>
                  </li>
                </ul>
            </li>

            </ul>
          </div>
        </section>
      </div>
    </div>
  </section>
 <div class="clearfix"></div>

 <!-- booking fancy form : start -->
 <%= form_for @booking, :url => { :action => :create }, :html =>{ :style => 'display : none', :id => 'registration_form'} do |f| %>
    <fieldset>
      <p>
        <%= f.label :user_name, "Name" %><br />
        <%= f.text_field :user_name %>
      </p>
      <p>
        <%= f.label :phone_number, "Phone" %><br />
        <%= f.text_field :phone_number %>
      </p>
      <p>
        <%= f.label :email, "Email" %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :time_slot, "DateTime" %><br />
        <%= f.text_field :time_slot %>
      </p>
        <input type="hidden" name="booking[table_id]" id="table_id" />
        <input type="submit" value="Register" class="btn btn-large pull-right" />
    </fieldset>
<% end %><!-- booking fancy form : end -->

app/views/galleries/new.html.erb
<%= form_for @gallery,:url=> {:action => "create"} do |f| %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <%= f.fields_for :images do |i| %>
   <%= i.file_field :data %>
  <% end %>
  <p><%= f.submit "Submit" %></p>
<% end %>

<script type=text/javascript>
    $(document).ready(function(){
        var gallery_title = new LiveValidation( 'gallery_title', {validMessage:" ",onlyOnSubmit: true } );
        gallery_title.add( Validate.Presence);
    });
</script>

app/views/home/index.html.erb
 <%= javascript_include_tag "home" %>
  <section class="homeSearchFullWrap">
    <div class="container">
      <div class="searchPanel">
        <select name="country_id" class="selectCity" id="country_id" tabindex="1">
          <option value ="pune">Pune</option>
          <option value = "mumbai">Mumbai</option>
        </select>
      </div>
    </div>
  </section>
  <section class="cityHotelList">
    <div class="container">
      <div class="row">
        <ul class="hotelList">
          <% @hotels.each do |hotel|%>
          <li class="<%= hotel.city %>_selected">
            <a href="<%= new_hotel_booking_path(hotel) %>">
              <img src="<%= hotel.main_image %>">
              <span class="hotelName"><%= hotel.name %></span>
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </section>

app/views/hotels/dashboard.html.erb
<% if current_user.hotel.present? %>
    <%= link_to "Edit Hotel Detail", new_hotel_path,:class=>"btn btn-primary btn-large"%>
<% else %>
    <%= link_to "Add Hotel Detail", new_hotel_path,:class=>"btn btn-primary btn-large"%>
<% end %>
<!--<%#= link_to "Add New Hotel", new_hotel_path,:class=>"btn btn-primary btn-large"%>-->
<div></div>

<% if @hotel.present? %>
<h1>Hotel Details</h1>
<table class="table table-hover">
  <thead>
  <tr>

    <th>Name</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>City</th>
    <th>Hotel Images</th>
    <th>Bookings</th>
  </tr>
  </thead>
  <tbody>

      <tr>
        <td><%= @hotel.name %></td>
        <td><%= @hotel.address %></td>
        <td><%= @hotel.phone_number %></td>
        <td><%= @hotel.city %></td>
        <td><%= link_to "Add Images", new_hotel_gallery_path(@hotel) %></td>
        <td><%= link_to "Show Bookings", hotel_bookings_path(@hotel) %></td>
      </tr>
  </tbody>
</table>
<% end %>

app/views/hotels/new.html.erb
<h1>Add New Hotel</h1>
<div class="span5">
  <%= form_for @hotel, :multipart => true, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, "Name", :class => 'control-label'  %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, "Address", :class => 'control-label'  %>
      <div class="controls">
        <%= f.text_field :address %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :city, "City", :class => 'control-label'  %>
      <div class="controls">
        <%= f.text_field :city %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :website, "Website-Url", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :website, :placeholder => 'http://www.website.com'  %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :phone_number, "Phone", :class => 'control-label'  %>
      <div class="controls">
        <%= f.text_field :phone_number %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :main_image, "Hotel Image", :class => 'control-label'  %>
      <div class="controls">
        <%= f.file_field :main_image %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls" id="webo-new-post-submit-btn">
        <%= f.submit "Save",:class => "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

<script type=text/javascript>
    $(document).ready(function(){
    var hotel_name = new LiveValidation( 'hotel_name', {validMessage:" ",onlyOnSubmit: true } );
    hotel_name.add( Validate.Presence);
    var hotel_address = new LiveValidation( 'hotel_address', {validMessage:" ",onlyOnSubmit: true } );
    hotel_address.add( Validate.Presence);
    var hotel_city = new LiveValidation( 'hotel_city', {validMessage:" ",onlyOnSubmit: true } );
    hotel_city.add( Validate.Presence);
    var hotel_website =  new LiveValidation( 'hotel_website', {validMessage:" ",onlyOnSubmit: true } );
    hotel_website.add( Validate.Presence);
    var hotel_phone_number = new LiveValidation( 'hotel_phone_number', {validMessage:" ",onlyOnSubmit: true } );
        hotel_phone_number.add( Validate.Presence);
    });
</script>

app/views/layouts/_footer.html.erb
<section class="footer">
  <p class="copyrightTxt">&copy; Webonise Lab Pvt. Ltd. Pune </p>
</section>

app/views/layouts/_header.html.erb
    <div class="row">
      <div class="span5 pull-left">
        <h3 class="logo"><a href="#">Hot-Tab-Booking</a></h3>
      </div>
      <div class="span3 topContactDetails pull-right">
        <h4>Call Us : 123 456 7890</h4>
        <ul class="loginDetails">
        <% if !current_user %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => ""  %></li>
        <% end %>          
        </ul>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Welcome to Hot Table Booking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <section class="fullWrap">
      <section class="headerWrap">
        <div class="container">
      <%= render :partial => 'layouts/header'%>
      <%= yield %>
        </div>
      <%= render :partial => 'layouts/footer'%>

      </section>
    </section>
      <!-- Javascripts
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>